default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    build_ios_app(workspace: "Encryption.xcworkspace", scheme: "Encryption")
  end

  desc "Upload IPA to App Store Connect"
  lane :upload_to_app_store do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY"],
      in_house: false, # Set to `true` if you're using an Enterprise account
    )

    pilot(
      api_key: api_key,
      ipa: "derived_data/Build/Products/Release-iphoneos/Encryption.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end